Repository AY2425S2-CS2113-F14-1/tp, pull requests merged in 2025-04, with the labels that each got.

#65 Update UserGuide.md
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#67 UG Fix
  docs/UserGuide.md
Labels: severity.VeryLow, type.Bug

#69 Zixi ppp
  docs/DeveloperGuide.md
  docs/Images/AddDiagram.png
  docs/Images/ClassDiagram.png
  docs/Images/TransactionDiagram.png
  docs/Images/list.png
  docs/Images/tick.png
  docs/Images/untick.png
  docs/UML/add.puml
  docs/UML/list.puml
  docs/UML/tick.puml
  docs/UML/untick.puml
  docs/team/halfentise.md
  src/main/java/seedu/duke/Transaction.java
  src/main/java/seedu/duke/TransactionManager.java
Labels: priority.High

#75 Fixed UG and DG formatting issues
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
Labels: severity.VeryLow, type.Bug, priority.Medium

#76 Added diagrams
  docs/DeveloperGuide.md
  docs/Images/GoalDiagram.png
  docs/Images/setRecur.png
  docs/Screenshots/Alert_demo.png
  docs/Sequence_Diagrams_pics/SetBudget.png
  docs/UML/classFinancialGoal.puml
  docs/UML/setRecurringPeriod.puml
  docs/UserGuide.md
  src/main/java/parser/Parser.java
Labels: severity.Low, priority.High, type.Task

#154 Enhance category parsing with case-insensitive input and fallback UI selection
  README.md
  src/main/java/parser/Parser.java
Labels: severity.Medium, priority.High
